name 'dummy3'
description 'A basic starter cookbook.'
version '1.0.0'
maintainer 'Awesome Company, Inc.'
maintainer_email 'you@example.com'
# issues_url 'https://github.com/<insert_org_here>/pbisht-dummy2/issues'
# source_url 'https://github.com/<insert_org_here>/pbisht-dummy2'
